"""add_min_stock_threshold

Revision ID: 282abfadc79d
Revises: 2ec3c3c3fa76
Create Date: 2026-06-15 02:29:45.281182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '282abfadc79d'
down_revision: Union[str, Sequence[str], None] = '2ec3c3c3fa76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventories', sa.Column('min_stock_threshold', sa.Integer(), server_default='5', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventories', 'min_stock_threshold')
    # ### end Alembic commands ###
